FROM python:3-alpine3.15
WORKDIR /chatbot
COPY . /chatbot
RUN pip install -r requirements.txt
EXPOSE 3000
ENV OPENAI_API_KEY='sk-proj-nXikom3d4WihoE2AYbVRT3BlbkFJ1aXMFgAzY5pJy6tBVRGB'         
CMD python ./app.py
